// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "InkVisionPackage",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "InkVision",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.InkVision",
            teamIdentifier: "YOUR_TEAM_ID",
            displayVersion: "1.0.3",
            bundleVersion: "4",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            capabilities: [
                .camera(purposeString: "InkVision needs camera access to show tattoos on your arm.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)